model = dict(
    task_mode="semantic",
    bpe_path="assets/bpe_simple_vocab_16e6.txt.gz",
    checkpoint_path="weights/sam3.pt",
    load_from_hf=False,
    device="cuda",
    eval_mode=False,
    compile=False,
    prompt_chunk_size=8,

    openclip_cfg=dict(
        enabled=True,
        model_name="ViT-L-14",
        pretrained="weights/RemoteCLIP-ViT-L-14.pt",
        default_output="feat_map",
        image_size=504,
        image_intermediate_layers=[7, 15],

        prompt_templates=[
            "a remote sensing image of {}.",
            "a satellite image of {}.",
            "an aerial image of {}.",
            "a high-resolution overhead image of {}.",
            "a top-down view of {}.",
            "a bird's-eye view image of {}.",
            "a remote sensing scene containing {}.",
            "a satellite scene containing {}.",
            "an aerial scene containing {}.",
            "a high-resolution remote sensing scene of {}.",
            "a land cover region of {} in a satellite image.",
            "a land use area of {} in an aerial image.",
            "a semantic segmentation region of {}.",
            "a labeled mask region corresponding to {}.",
            "a continuous area of {} in overhead imagery.",
            "a visible region of {} from above.",
            "the texture pattern of {} in a satellite image.",
            "the spatial pattern of {} in remote sensing imagery.",
            "the shape and boundary of {} in an aerial image.",
            "the object boundary of {} from an overhead view.",
            "a small-scale remote sensing object of {}.",
            "a large-scale remote sensing region of {}.",
            "multiple instances of {} in a satellite image.",
            "dense objects of {} in overhead imagery.",
            "sparse objects of {} in remote sensing imagery.",
            "urban remote sensing imagery showing {}.",
            "rural remote sensing imagery showing {}.",
            "natural land surface containing {}.",
            "man-made structures containing {}.",
            "a homogeneous area of {}.",
            "a complex background with {}.",
            "an object or region classified as {} in remote sensing imagery.",
        ],
        normalize_label_for_clip=True,
        text_prompt_batch_size=64,
        text_prompt_use_checkpoint=True,
    ),

    encoder_refiner_cfg=dict(
        enabled=True,
        fusion_layers=4,
        num_heads=8,
        dropout=0.1,
        hidden_dim=256,

        score_embed_dim=256,
        layer_scale_init=0.1,

        refiner_hw=36,
        encoder_hw=72,

        window_size=12,
        shift_size=6,

        use_checkpoint=True,
        early_prompt_attention=False,
    ),

    freeze_cfg=dict(
        train_adapters_only=True,
        trainable_modules=[
            "core.encoder_refiner",
        ],
        frozen_modules=[],
        openclip_text_finetune="attention",
        openclip_image_finetune="attention",
    ),

    adapter_cfg=dict(
        class_relative_prob_thd=0.2,
        class_relative_eps=1e-6,
    ),

    criterion_cfg=dict(
        ignore_index=255,
        final_bce_weight=1.0,
        final_dice_weight=0.0,
        bce_absent_class_weight=0.05,
        bce_valid_pixel_weight=1.0,
        bce_ignore_pixel_weight=0.05,
        eps=1e-6,
    ),
)
