program: tools/train.py
name: full_isaid_loveda_final_v1
method: grid

metric:
  name: val/semantic.miou
  goal: maximize

parameters:
  experiment_tracking.wandb.enabled:
    value: true

  experiment_tracking.wandb.project:
    value: ovrs-sam3

  experiment_tracking.wandb.group:
    value: full_isaid_loveda

  experiment_tracking.wandb.name:
    value: full_isaid_loveda_final_v1

  experiment_tracking.wandb.tags:
    value:
      - full
      - isaid-train
      - loveda-val
      - final-design
      - fixed-32-templates
      - score-dim-256

  visualization.enabled:
    value: true

command:
  - ${env}
  - ${interpreter}
  - ${program}
  - configs/train/isaid_loveda_full.py

  - --work-dir
  - work_dirs/full/isaid_loveda_final_v1

  - --seed
  - "42"

  - --cfg-options
  - ${args_no_hyphens}
